import { writeFile } from "node:fs/promises";

await writeFile(
  "src/generated/database.types.ts",
  `// Generated by \\`npm run db:types\\`. Do not edit by hand.
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
        };
      };
    };
  };
}
`,
  "utf8"
);
